# Configuration for auto-assign - https://github.com/kentaro-m/auto-assign

addReviewers: true
numberOfReviewers: 0 # will add all reviewers
reviewers:
  - y0hami
  - ColinFrick
  - prudho
  - lubber-de
  - ko2in
